### ISSUE TITLE
recordChangeDate: ISO 8601 na úroveň minut

### ISSUE THREAD

**Issue by rzeh4n** [rzeh4n/validator-e-publikaci#1]
U DMF [eborn_periodika_2.3](https://old.ndk.cz/standardy-digitalizace/DMF_ebornperiodika_2.3.pdf) se u recordChangeDate vždy uvádí, že tam má být datum na úrovni minut. Stejně tak pro eborn monografie.
Vidím dvě možné interpretace:

1. právě na úroveň minut, takže 20210309T1955 je platné, ale 20210309T195538 (i sekundy) není
2.alespoň na úroveň minut, takže je validní 20210309T1955 ji 20210309T195538

Objevil jsem to u jednoho ukázkového balíku, je tam právě ta varianta i se sekundami.
Takže asi povolit i sekundy při validaci, byl to záměr? Každopádně v dalších verzích DMF bych doporučil to formulovat jednoznačněji, jakože "alespoň na úroveň minut", případně "právě/přesně na úroveň minut".

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
s kolegami sme dospeli k záveru, že správnejšia interpretácia je tá druhá, tj. "alespoň na úroveň minut, takže je validní 20210309T1955 ji 20210309T195538". Ďakujeme za návrh presnejšej formulácie; pri najbližšej príležitosti to bude upravené na "alespoň na úroveň minut".

**Comment by rzeh4n** [comment]
Ok, upravím validátor, aby přijímal i hodnoty se sekundami.

**Comment by rzeh4n** [comment]
Povolil jsem tam i milisekundy, takže např.:
20190830T153559.123
2019-08-30T15:35:59.123Z

**Comment by rzeh4n** [comment]
Doplnil jsem validaci pro LASTMODDATE a CREATEDATE, tam jsem právě našel v datech hodnoty s milisekundami. @MirkaBenackova tam by teda bylo taky vhodné uvést "alespoň na úroveň sekund".

**Comment by rzeh4n** [comment]
Opraveno, bude součástí příštího releasu (aktuální verze je 1.2).

**Comment by MirkaBenackova** [comment]
> Doplnil jsem validaci pro LASTMODDATE a CREATEDATE, tam jsem právě našel v datech hodnoty s milisekundami. @MirkaBenackova tam by teda bylo taky vhodné uvést "alespoň na úroveň sekund".

V poriadku, poznamenala som si aj toto a pri ďalšej príležitosti bude aj táto fomulácia v DMF spresnená.
